apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: amazon/aws-ebs-csi-driver
  newTag: latest
  newName: gajanankulkarni09/aws-ebs-csi-driver
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ebs-csi-controller
  path: patch.yaml
patchesStrategicMerge:
- controller_add_snapshotter.yaml
- controller_add_resizer.yaml
resources:
- rbac_add_resizer_clusterrole.yaml
- rbac_add_resizer_clusterrolebinding.yaml
- rbac_add_snapshot_controller_clusterrole.yaml
- rbac_add_snapshot_controller_clusterrolebinding.yaml
- rbac_add_snapshot_controller_leaderelection_role.yaml
- rbac_add_snapshot_controller_leaderelection_rolebinding.yaml
- rbac_add_snapshotter_clusterrole.yaml
- rbac_add_snapshotter_clusterrolebinding.yaml
- serviceaccount-snapshot-controller.yaml
- snapshot_controller.yaml
