apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
- name: amazon/aws-ebs-csi-driver
  newTag: latest
  newName: gajanankulkarni09/aws-ebs-csi-driver
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ebs-csi-controller
  path: patch.yaml
